version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    networks:
      - my-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "27017:27017"
    # MONGODB_VOLUME对应的路径变量，会在项目根目录创建文件夹，文件夹内部的文件会和设置的容器中的文件夹同步（/data/db、/data/configdb）
    # 和容器里面数据库存储的数据保存位置相关的就是/data/db、/data/configdb
    volumes:
      - ${MONGODB_VOLUME}:/data/db
      - ${MONGODB_VOLUME}:/data/configdb

# 容器内容器外一致可以通信（容器外部可以成功连接到容器内部的数据库）
networks:
  my-network:
    driver: bridge